using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System;
using System.Linq;
using System.Text;

namespace HyperJet.Generators
{
    [Generator]
    public class DDScalarGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(postInitContext =>
            {
                // Generate global usings for backward compatibility
                var usingsBuilder = new StringBuilder();
                usingsBuilder.AppendLine("// <auto-generated />");
                for (int n = 1; n <= 15; n++)
                {
                    usingsBuilder.AppendLine($"global using DDScalar{n} = HyperJet.DDScalar{n}<double>;");
                    usingsBuilder.AppendLine($"global using DScalar{n} = HyperJet.DScalar{n}<double>;");
                }
                postInitContext.AddSource("GlobalUsings.g.cs", usingsBuilder.ToString());

                // Generate DDScalar1<T>..DDScalar15<T> (value, gradient and Hessian) and
                // DScalar1<T>..DScalar15<T> (value and gradient only) from the same template.
                for (int n = 1; n <= 15; n++)
                {
                    postInitContext.AddSource($"DDScalar{n}.g.cs", GenerateScalarStruct(n, order: 2));
                    postInitContext.AddSource($"DScalar{n}.g.cs", GenerateScalarStruct(n, order: 1));
                }

                postInitContext.AddSource("Buffers.g.cs", GenerateBuffers());

                // Generate the HyperJetMath free-function overloads for every dimension
                postInitContext.AddSource("HyperJetMath.Static.g.cs", GenerateHyperJetMathOverloads());
            });
        }

        /// <summary>
        /// Functions that take a single dual number and return one. Forwarded verbatim to the
        /// corresponding generic-math member of the struct.
        /// </summary>
        private static readonly string[] UnaryFunctions =
        {
            "Sin", "Cos", "Tan", "Asin", "Acos", "Atan",
            "SinPi", "CosPi", "TanPi", "AsinPi", "AcosPi", "AtanPi",
            "Exp", "Exp2", "Exp10", "ExpM1",
            "Log", "Log2", "Log10", "LogP1",
            "Sinh", "Cosh", "Tanh", "Asinh", "Acosh", "Atanh",
            "Sqrt", "Cbrt", "Abs",
        };

        /// <summary>
        /// Emits the half of <c>HyperJetMath</c> that serves the generated structs, so that
        /// <c>using static HyperJet.HyperJetMath;</c> offers <c>Sin(x)</c> for every dimension and not
        /// just for one. Everything here forwards, so there is no second copy of a derivative formula
        /// that could drift away from the struct's own.
        /// </summary>
        private static string GenerateHyperJetMathOverloads()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Numerics;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace HyperJet");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class HyperJetMath");
            sb.AppendLine("    {");

            foreach (string family in new[] { "DDScalar", "DScalar" })
            for (int n = 1; n <= 15; n++)
            {
                string type = $"{family}{n}<T>";
                const string where = "where T : IFloatingPointIeee754<T>";

                sb.AppendLine($"        #region {family}{n} Functions");
                sb.AppendLine();

                foreach (string name in UnaryFunctions)
                {
                    sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine($"        public static {type} {name}<T>(in {type} a) {where} => {type}.{name}(a);");
                    sb.AppendLine();
                }

                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Atan2<T>(in {type} y, in {type} x) {where} => {type}.Atan2(y, x);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Atan2Pi<T>(in {type} y, in {type} x) {where} => {type}.Atan2Pi(y, x);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Hypot<T>(in {type} a, in {type} b) {where} => {type}.Hypot(a, b);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Log<T>(in {type} a, in {type} newBase) {where} => {type}.Log(a, newBase);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Pow<T>(in {type} a, in {type} b) {where} => {type}.Pow(a, b);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} RootN<T>(in {type} a, int n) {where} => {type}.RootN(a, n);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Ieee754Remainder<T>(in {type} a, in {type} b) {where} => {type}.Ieee754Remainder(a, b);");
                sb.AppendLine();
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Identical to <c>Ieee754Remainder</c>. .NET carries this function under two names --");
                sb.AppendLine("        /// <c>Math.IEEERemainder</c> predates the naming guideline that gave the generic-math");
                sb.AppendLine("        /// surface <c>Ieee754Remainder</c> -- and this facade mirrors <c>System.Math</c>, so it");
                sb.AppendLine("        /// offers the spelling a caller coming from there will reach for.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} IEEERemainder<T>(in {type} a, in {type} b) {where} => {type}.Ieee754Remainder(a, b);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} FusedMultiplyAdd<T>(in {type} x, in {type} y, in {type} z) {where} => {type}.FusedMultiplyAdd(x, y, z);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static ({type} Sin, {type} Cos) SinCos<T>(in {type} a) {where} => {type}.SinCos(a);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static ({type} SinPi, {type} CosPi) SinCosPi<T>(in {type} a) {where} => {type}.SinCosPi(a);");
                sb.AppendLine();

                // A constant exponent never needs log(a), so unlike the two-operand overload this
                // one also works for a negative base.
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Raises <paramref name=\"a\"/> to a constant power. Unlike the two-operand overload this");
                sb.AppendLine("        /// never evaluates <c>log(a)</c>, so it also works for a negative base.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Pow<T>(in {type} a, T b) {where}");
                sb.AppendLine("        {");
                sb.AppendLine("            T two = T.One + T.One;");
                sb.AppendLine("            T f = T.Pow(a.Value, b);");
                sb.AppendLine("            T da = b * T.Pow(a.Value, b - T.One);");
                sb.AppendLine("            T daa = (b - T.One) * b * T.Pow(a.Value, b - two);");
                sb.AppendLine();
                sb.AppendLine($"            {type} result = default;");
                sb.AppendLine("            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(");
                sb.AppendLine("                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),");
                sb.AppendLine($"                result.AsSpan(), {type}.Size, {type}.Order);");
                sb.AppendLine("            return result;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        #endregion");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string[] GetVariableNames(int n)
        {
            if (n == 1) return new[] { "x" };
            if (n == 2) return new[] { "x", "y" };
            if (n == 3) return new[] { "x", "y", "z" };
            if (n == 4) return new[] { "x", "y", "z", "w" };
            
            var names = new string[n];
            for (int i = 0; i < n; i++)
            {
                names[i] = $"v{i + 1}";
            }
            return names;
        }

        /// <summary>
        /// Emits one scalar struct. <paramref name="order"/> selects the family: second order
        /// (<c>DDScalar{n}</c>, value + gradient + Hessian) or first order (<c>DScalar{n}</c>,
        /// value + gradient). Both come from this one template so the derivative formulas exist once.
        /// </summary>
        private string GenerateScalarStruct(int n, int order)
        {
            int size = n;
            bool secondOrder = order == 2;
            string scalar = secondOrder ? $"DDScalar{n}" : $"DScalar{n}";
            int dataLength = secondOrder ? (n + 1) * (n + 2) / 2 : n + 1;

            // A line that only a second-order scalar needs. The kernels ignore the second-derivative
            // coefficients when order is 1, so computing them there would be dead work -- and for
            // Pow or RootN that dead work is a call to Pow.
            string D2(string name, string expr) => secondOrder ? $"            T {name} = {expr};\n" : "";

            // The matching argument. The coefficient type stays as it is: at order 1 the kernel
            // returns before it is read, and keeping the type shares the generic instantiation with
            // the second-order family instead of doubling it.
            string A2(string argument) => secondOrder ? argument : "default";

            // A first-order scalar stores no Hessian, so it exposes no way to read one.
            string hessianAccessors = !secondOrder ? "" : $@"        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T H(int i, int j)
        {{
            if (i < 0 || i >= Size) throw new ArgumentOutOfRangeException(nameof(i));
            if (j < 0 || j >= Size) throw new ArgumentOutOfRangeException(nameof(j));

            int index = GetHessianIndex(i, j);
            return _data[index];
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetH(int i, int j, T value)
        {{
            if (i < 0 || i >= Size) throw new ArgumentOutOfRangeException(nameof(i));
            if (j < 0 || j >= Size) throw new ArgumentOutOfRangeException(nameof(j));

            int index = GetHessianIndex(i, j);
            _data[index] = value;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static int GetHessianIndex(int i, int j)
        {{
            if (i < j)
            {{
                return 1 + Size + (2 * Size - 1 - i) * i / 2 + j;
            }}
            else
            {{
                return 1 + Size + (2 * Size - 1 - j) * j / 2 + i;
            }}
        }}

";

            string hessianExport = !secondOrder ? "" : $@"        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T[,] GetHessian()
        {{
            T[,] h = new T[Size, Size];
            for (int i = 0; i < Size; i++)
                for (int j = 0; j < Size; j++)
                    h[i, j] = H(i, j);
            return h;
        }}

";

            // Without a Hessian the Taylor expansion degenerates to the linear model.
            string quadraticTerm = !secondOrder ? "" : $@"            // The Hessian is stored as the upper triangle in row order, so a single pass reaches
            // H[i,i] first and then H[i,j] for j > i. Each off-diagonal coefficient stands for two
            // symmetric terms of the quadratic form, which is exactly what cancels the one half.
            T half = T.One / (T.One + T.One);

            int k = 1 + Size;
            for (int i = 0; i < Size; i++)
            {{
                T di = d[i];
                result += half * data[k++] * di * di;

                for (int j = i + 1; j < Size; j++)
                {{
                    result += data[k++] * di * d[j];
                }}
            }}

";

            string orderText = secondOrder
                ? "2nd order (value, gradient and Hessian)"
                : "1st order (value and gradient)";
            string variableWord = n == 1 ? "variable" : "variables";

            var variableNames = GetVariableNames(n);

            // ToString has to enumerate this dimension's coefficients. Spelling it out for two
            // variables made DDScalar1 throw from G(1) and every dimension above two print a
            // truncated gradient and Hessian.
            string gradientText = string.Join(", ", Enumerable.Range(0, n).Select(i => $"{{G({i})}}"));
            string hessianText = !secondOrder ? "" : ", H: (" + string.Join(", ", Enumerable.Range(0, n).Select(i =>
                "(" + string.Join(", ", Enumerable.Range(0, n).Select(j => $"{{H({i}, {j})}}")) + ")")) + ")";

            // A fixed-arity companion to Evaluate(ReadOnlySpan<T>), so that passing the wrong number
            // of offsets to a compile-time-sized scalar is a compile error rather than a throw. The
            // span local makes the target overload unambiguous; it is stack-allocated.
            var offsetParameters = string.Join(", ", Enumerable.Range(0, n).Select(i => $"T d{i}"));
            var offsetElements = string.Join(", ", Enumerable.Range(0, n).Select(i => $"d{i}"));
            string evaluateOverload = $@"        /// <summary>
        /// Evaluates the second-order Taylor expansion around the point this value was computed at.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T Evaluate({offsetParameters})
        {{
            ReadOnlySpan<T> d = [{offsetElements}];
            return Evaluate(d);
        }}";

            string variablesFactory;
            if (n == 1)
            {
                variablesFactory = $@"
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> Variables(T xVal)
        {{
            return Variable(0, xVal);
        }}
";
            }
            else
            {
                var paramsList = string.Join(", ", variableNames.Select(v => $"T {v}Val"));
                var tupleTypes = string.Join(", ", variableNames.Select(v => $"{scalar}<T> {v}"));
                var returnValues = string.Join(", ", variableNames.Select((v, idx) => $"Variable({idx}, {v}Val)"));
                variablesFactory = $@"
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ({tupleTypes}) Variables({paramsList})
        {{
            return ({returnValues});
        }}
";
            }

            return $@"// <auto-generated />
#nullable enable
using System;
using System.Globalization;
using System.Numerics;
using System.Runtime.CompilerServices;

namespace HyperJet
{{
    /// <summary>
    /// Represents a {orderText} dual number with {n} static {variableWord} (Zero-Allocation, Stack-Allocated).
    /// </summary>
    public struct {scalar}<T> : 
        IFloatingPointIeee754<{scalar}<T>>,
        ITrigonometricFunctions<{scalar}<T>>,
        IExponentialFunctions<{scalar}<T>>,
        IHyperbolicFunctions<{scalar}<T>>,
        ILogarithmicFunctions<{scalar}<T>>,
        IPowerFunctions<{scalar}<T>>,
        IRootFunctions<{scalar}<T>>
        where T : IFloatingPointIeee754<T>
    {{
        public const int Size = {size};
        public const int Order = {order};
        public const int DataLength = {dataLength};

        private Buffer{dataLength}<T> _data;

        public T Value
        {{
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            readonly get => _data[0];
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => _data[0] = value;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T G(int i)
        {{
            if (i < 0 || i >= Size)
                throw new ArgumentOutOfRangeException(nameof(i));
            return _data[1 + i];
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetG(int i, T value)
        {{
            if (i < 0 || i >= Size)
                throw new ArgumentOutOfRangeException(nameof(i));
            _data[1 + i] = value;
        }}

{hessianAccessors}        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Span<T> AsSpan()
        {{
            return System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref Unsafe.As<Buffer{dataLength}<T>, T>(ref _data), DataLength);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly ReadOnlySpan<T> AsReadOnlySpan()
        {{
            return System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref Unsafe.As<Buffer{dataLength}<T>, T>(ref Unsafe.AsRef(in _data)), DataLength);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T[] GetGradient()
        {{
            T[] g = new T[Size];
            for (int i = 0; i < Size; i++) g[i] = G(i);
            return g;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void GetGradient(Span<T> destination)
        {{
            if (destination.Length < Size) throw new ArgumentException(""Destination span is too small."", nameof(destination));
            for (int i = 0; i < Size; i++) destination[i] = G(i);
        }}

{hessianExport}        /// <summary>
        /// Evaluates the second-order Taylor expansion of the represented function around the point
        /// it was evaluated at: <c>f(x + d) = f(x) + grad(f) . d + 1/2 d^T H d</c>.
        /// </summary>
        /// <param name=""d"">The offset from the expansion point, one component per variable.</param>
        /// <remarks>
        /// For a function that is itself quadratic the expansion is exact; otherwise the error is
        /// O(|d|^3). This is the local quadratic model used by a trust-region step or a line search.
        /// </remarks>
        public readonly T Evaluate(params ReadOnlySpan<T> d)
        {{
            if (d.Length != Size)
                throw new ArgumentException($""Expected {{Size}} offsets, got {{d.Length}}."", nameof(d));

            ReadOnlySpan<T> data = AsReadOnlySpan();
            T result = data[0];

            for (int i = 0; i < Size; i++)
            {{
                result += data[1 + i] * d[i];
            }}

{quadraticTerm}            return result;
        }}

{evaluateOverload}

        #region Constructors and Factory Methods

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public {scalar}(T value)
        {{
            _data = default;
            _data[0] = value;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> Constant(T value)
        {{
            return new {scalar}<T>(value);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> Variable(int index, T value)
        {{
            if (index < 0 || index >= Size)
                throw new ArgumentOutOfRangeException(nameof(index));

            {scalar}<T> result = default;
            result.Value = value;
            result.SetG(index, T.One);
            return result;
        }}

{variablesFactory}

        #endregion

        #region Operators

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator -({scalar}<T> a)
        {{
            {scalar}<T> result = default;
            for (int i = 0; i < DataLength; i++)
            {{
                result._data[i] = -a._data[i];
            }}
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator +({scalar}<T> a, {scalar}<T> b)
        {{
            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, OneCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), a.Value + b.Value,
                default, default, default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator +({scalar}<T> a, T b)
        {{
            {scalar}<T> result = a;
            result.Value += b;
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator +(T a, {scalar}<T> b) => b + a;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator -({scalar}<T> a, {scalar}<T> b)
        {{
            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, MinusOneCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), a.Value - b.Value,
                default, default, default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator -({scalar}<T> a, T b)
        {{
            {scalar}<T> result = a;
            result.Value -= b;
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator -(T a, {scalar}<T> b)
        {{
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, MinusOneCoeff<T>, ZeroCoeff<T>>(
                b.AsReadOnlySpan(), a - b.Value, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator *({scalar}<T> a, {scalar}<T> b)
        {{
            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, OneCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), a.Value * b.Value,
                new ValueCoeff<T>(b.Value), new ValueCoeff<T>(a.Value), default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator *({scalar}<T> a, T b)
        {{
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), a.Value * b, new ValueCoeff<T>(b), default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator *(T a, {scalar}<T> b) => b * a;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator /({scalar}<T> a, {scalar}<T> b)
        {{
            T tmp = T.One / b.Value;
            T f = a.Value * tmp;
            T da = tmp;
            T db = -a.Value * tmp * tmp;
{D2("dab", "-tmp * tmp")}{D2("dbb", "T.CreateChecked(2.0) * a.Value * tmp * tmp * tmp")}
            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), default, {A2("new ValueCoeff<T>(dab)")}, {A2("new ValueCoeff<T>(dbb)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator /({scalar}<T> a, T b) => a * (T.One / b);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator /(T a, {scalar}<T> b)
        {{
            T tmp = T.One / b.Value;
            T f = a * tmp;
            T db = -a * tmp * tmp;
{D2("dbb", "T.CreateChecked(2.0) * a * tmp * tmp * tmp")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                b.AsReadOnlySpan(), f, new ValueCoeff<T>(db), {A2("new ValueCoeff<T>(dbb)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator %({scalar}<T> a, {scalar}<T> b)
        {{
            // C# defines a % b as a - b * truncate(a / b) — the quotient is rounded towards zero,
            // not downwards, so Truncate (and not Floor) yields the derivative with respect to b.
            T k = T.Truncate(a.Value / b.Value);
            T f = a.Value % b.Value;
            T db = -k;

            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), f,
                default, new ValueCoeff<T>(db), default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator +({scalar}<T> a) => a;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator ++({scalar}<T> a) => a + T.One;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static {scalar}<T> operator --({scalar}<T> a) => a - T.One;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator {scalar}<T>(T value)
        {{
            return Constant(value);
        }}

        #endregion

        #region Comparisons

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==({scalar}<T> a, {scalar}<T> b) => a.Value == b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=({scalar}<T> a, {scalar}<T> b) => a.Value != b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <({scalar}<T> a, {scalar}<T> b) => a.Value < b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >({scalar}<T> a, {scalar}<T> b) => a.Value > b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <=({scalar}<T> a, {scalar}<T> b) => a.Value <= b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >=({scalar}<T> a, {scalar}<T> b) => a.Value >= b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==({scalar}<T> a, T b) => a.Value == b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=({scalar}<T> a, T b) => a.Value != b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <({scalar}<T> a, T b) => a.Value < b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >({scalar}<T> a, T b) => a.Value > b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <=({scalar}<T> a, T b) => a.Value <= b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >=({scalar}<T> a, T b) => a.Value >= b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(T a, {scalar}<T> b) => a == b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(T a, {scalar}<T> b) => a != b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <(T a, {scalar}<T> b) => a < b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >(T a, {scalar}<T> b) => a > b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <=(T a, {scalar}<T> b) => a <= b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >=(T a, {scalar}<T> b) => a >= b.Value;

        public override readonly bool Equals(object? obj) => obj is {scalar}<T> other && this == other;

        public readonly bool Equals({scalar}<T> other) => Value == other.Value;

        public override readonly int GetHashCode() => Value is null ? 0 : Value.GetHashCode();

        #endregion

        #region Generic Math Support (IFloatingPoint etc.)

        public static {scalar}<T> AdditiveIdentity => new {scalar}<T>(T.Zero);
        public static {scalar}<T> MultiplicativeIdentity => new {scalar}<T>(T.One);

        public static {scalar}<T> One => new {scalar}<T>(T.One);
        public static {scalar}<T> Zero => new {scalar}<T>(T.Zero);
        public static {scalar}<T> NegativeOne => new {scalar}<T>(-T.One);

        public static {scalar}<T> E => new {scalar}<T>(T.E);
        public static {scalar}<T> Pi => new {scalar}<T>(T.Pi);
        public static {scalar}<T> Tau => new {scalar}<T>(T.Tau);

        // IEEE 754 special values. Like every other constant these carry no derivatives.
        public static {scalar}<T> Epsilon => new {scalar}<T>(T.Epsilon);
        public static {scalar}<T> NaN => new {scalar}<T>(T.NaN);
        public static {scalar}<T> PositiveInfinity => new {scalar}<T>(T.PositiveInfinity);
        public static {scalar}<T> NegativeInfinity => new {scalar}<T>(T.NegativeInfinity);
        public static {scalar}<T> NegativeZero => new {scalar}<T>(T.NegativeZero);

        public static int Radix => 2;

        public readonly int CompareTo(object? obj)
        {{
            if (obj is {scalar}<T> other) return Value.CompareTo(other.Value);
            throw new ArgumentException(""Object is not a DDScalar"");
        }}

        public readonly int CompareTo({scalar}<T> other) => Value.CompareTo(other.Value);

        public readonly string ToString(string? format, IFormatProvider? formatProvider) => Value is null ? string.Empty : Value.ToString(format, formatProvider);

        public readonly bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {{
            if (Value is ISpanFormattable formattable)
            {{
                return formattable.TryFormat(destination, out charsWritten, format, provider);
            }}
            charsWritten = 0;
            return false;
        }}

        public readonly bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {{
            if (Value is IUtf8SpanFormattable formattable)
            {{
                return formattable.TryFormat(utf8Destination, out bytesWritten, format, provider);
            }}
            bytesWritten = 0;
            return false;
        }}

        public static {scalar}<T> Parse(string s, IFormatProvider? provider) => new {scalar}<T>(T.Parse(s, provider));

        public static bool TryParse(string? s, IFormatProvider? provider, out {scalar}<T> result)
        {{
            if (T.TryParse(s, provider, out T? val))
            {{
                result = new {scalar}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static {scalar}<T> Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => new {scalar}<T>(T.Parse(s, provider));

        public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {scalar}<T> result)
        {{
            if (T.TryParse(s, provider, out T? val))
            {{
                result = new {scalar}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static {scalar}<T> Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider) => new {scalar}<T>(T.Parse(utf8Text, provider));

        public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out {scalar}<T> result)
        {{
            if (T.TryParse(utf8Text, provider, out T? val))
            {{
                result = new {scalar}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static {scalar}<T> Parse(string s, NumberStyles style, IFormatProvider? provider) => new {scalar}<T>(T.Parse(s, style, provider));

        public static {scalar}<T> Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) => new {scalar}<T>(T.Parse(s, style, provider));

        public static bool TryParse(string? s, NumberStyles style, IFormatProvider? provider, out {scalar}<T> result)
        {{
            if (T.TryParse(s, style, provider, out T? val))
            {{
                result = new {scalar}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out {scalar}<T> result)
        {{
            if (T.TryParse(s, style, provider, out T? val))
            {{
                result = new {scalar}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        private static bool TryConvertFromCheckedHelper<TDest, TOther>(TOther value, out TDest result) 
            where TDest : INumberBase<TDest> 
            where TOther : INumberBase<TOther>
        {{
            return TDest.TryConvertFromChecked(value, out result!);
        }}

        private static bool TryConvertFromSaturatingHelper<TDest, TOther>(TOther value, out TDest result) 
            where TDest : INumberBase<TDest> 
            where TOther : INumberBase<TOther>
        {{
            return TDest.TryConvertFromSaturating(value, out result!);
        }}

        private static bool TryConvertFromTruncatingHelper<TDest, TOther>(TOther value, out TDest result) 
            where TDest : INumberBase<TDest> 
            where TOther : INumberBase<TOther>
        {{
            return TDest.TryConvertFromTruncating(value, out result!);
        }}

        private static bool TryConvertToCheckedHelper<TSrc, TDest>(TSrc value, out TDest result)
            where TSrc : INumberBase<TSrc>
            where TDest : INumberBase<TDest>
        {{
            return TSrc.TryConvertToChecked(value, out result!);
        }}

        private static bool TryConvertToSaturatingHelper<TSrc, TDest>(TSrc value, out TDest result)
            where TSrc : INumberBase<TSrc>
            where TDest : INumberBase<TDest>
        {{
            return TSrc.TryConvertToSaturating(value, out result!);
        }}

        private static bool TryConvertToTruncatingHelper<TSrc, TDest>(TSrc value, out TDest result)
            where TSrc : INumberBase<TSrc>
            where TDest : INumberBase<TDest>
        {{
            return TSrc.TryConvertToTruncating(value, out result!);
        }}

        private static bool IsCanonicalHelper<TSrc>(TSrc value) where TSrc : INumberBase<TSrc> => TSrc.IsCanonical(value);
        private static bool IsZeroHelper<TSrc>(TSrc value) where TSrc : INumberBase<TSrc> => TSrc.IsZero(value);

        // A conversion between TOther and the coefficient type T needs the same two-step fallback
        // INumberBase.CreateChecked performs: ask the destination first, then the source. Neither
        // side handles the case TOther == T — CreateChecked normally short-circuits that itself, and
        // here it does not, because the nominal destination is {scalar}<T> rather than T.
        public static bool TryConvertFromChecked<TOther>(TOther value, out {scalar}<T> result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = new {scalar}<T>((T)(object)value!);
                return true;
            }}
            if (TryConvertFromCheckedHelper<T, TOther>(value, out T inner) || TryConvertToCheckedHelper<TOther, T>(value, out inner))
            {{
                result = new {scalar}<T>(inner);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryConvertFromSaturating<TOther>(TOther value, out {scalar}<T> result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = new {scalar}<T>((T)(object)value!);
                return true;
            }}
            if (TryConvertFromSaturatingHelper<T, TOther>(value, out T inner) || TryConvertToSaturatingHelper<TOther, T>(value, out inner))
            {{
                result = new {scalar}<T>(inner);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryConvertFromTruncating<TOther>(TOther value, out {scalar}<T> result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = new {scalar}<T>((T)(object)value!);
                return true;
            }}
            if (TryConvertFromTruncatingHelper<T, TOther>(value, out T inner) || TryConvertToTruncatingHelper<TOther, T>(value, out inner))
            {{
                result = new {scalar}<T>(inner);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryConvertToChecked<TOther>({scalar}<T> value, out TOther result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = (TOther)(object)value.Value!;
                return true;
            }}
            return TOther.TryConvertFromChecked(value.Value, out result!)
                || TryConvertToCheckedHelper<T, TOther>(value.Value, out result);
        }}

        public static bool TryConvertToSaturating<TOther>({scalar}<T> value, out TOther result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = (TOther)(object)value.Value!;
                return true;
            }}
            return TOther.TryConvertFromSaturating(value.Value, out result!)
                || TryConvertToSaturatingHelper<T, TOther>(value.Value, out result);
        }}

        public static bool TryConvertToTruncating<TOther>({scalar}<T> value, out TOther result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = (TOther)(object)value.Value!;
                return true;
            }}
            return TOther.TryConvertFromTruncating(value.Value, out result!)
                || TryConvertToTruncatingHelper<T, TOther>(value.Value, out result);
        }}

        public static {scalar}<T> Abs({scalar}<T> value) => value.Value < T.Zero ? -value : value;

        public static bool IsCanonical({scalar}<T> value) => IsCanonicalHelper(value.Value);
        public static bool IsComplexNumber({scalar}<T> value) => false;
        public static bool IsImaginaryNumber({scalar}<T> value) => false;
        public static bool IsEvenInteger({scalar}<T> value) => T.IsEvenInteger(value.Value);
        public static bool IsOddInteger({scalar}<T> value) => T.IsOddInteger(value.Value);
        public static bool IsFinite({scalar}<T> value) => T.IsFinite(value.Value);
        public static bool IsInfinity({scalar}<T> value) => T.IsInfinity(value.Value);
        public static bool IsInteger({scalar}<T> value) => T.IsInteger(value.Value);
        public static bool IsNaN({scalar}<T> value) => T.IsNaN(value.Value);
        public static bool IsNegative({scalar}<T> value) => T.IsNegative(value.Value);
        public static bool IsNegativeInfinity({scalar}<T> value) => T.IsNegativeInfinity(value.Value);
        public static bool IsNormal({scalar}<T> value) => T.IsNormal(value.Value);
        public static bool IsPositive({scalar}<T> value) => T.IsPositive(value.Value);
        public static bool IsPositiveInfinity({scalar}<T> value) => T.IsPositiveInfinity(value.Value);
        public static bool IsRealNumber({scalar}<T> value) => T.IsRealNumber(value.Value);
        public static bool IsSubnormal({scalar}<T> value) => T.IsSubnormal(value.Value);
        public static bool IsZero({scalar}<T> value) => IsZeroHelper(value.Value);

        public static {scalar}<T> MaxMagnitude({scalar}<T> x, {scalar}<T> y) => T.Abs(x.Value) >= T.Abs(y.Value) ? x : y;

        public static {scalar}<T> MaxMagnitudeNumber({scalar}<T> x, {scalar}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return MaxMagnitude(x, y);
        }}

        public static {scalar}<T> MinMagnitude({scalar}<T> x, {scalar}<T> y) => T.Abs(x.Value) < T.Abs(y.Value) ? x : y;

        public static {scalar}<T> MinMagnitudeNumber({scalar}<T> x, {scalar}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return MinMagnitude(x, y);
        }}

        public static {scalar}<T> Clamp({scalar}<T> value, {scalar}<T> min, {scalar}<T> max)
        {{
            if (min > max) throw new ArgumentException(""min cannot be greater than max"");
            if (value < min) return min;
            if (value > max) return max;
            return value;
        }}

        public static {scalar}<T> Max({scalar}<T> x, {scalar}<T> y) => x > y ? x : y;

        public static {scalar}<T> Min({scalar}<T> x, {scalar}<T> y) => x < y ? x : y;

        public static {scalar}<T> MaxNumber({scalar}<T> x, {scalar}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return x > y ? x : y;
        }}

        public static {scalar}<T> MinNumber({scalar}<T> x, {scalar}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return x < y ? x : y;
        }}

        public static {scalar}<T> Sign({scalar}<T> value) => new {scalar}<T>(T.CreateChecked(T.Sign(value.Value)));

        public static {scalar}<T> CopySign({scalar}<T> value, {scalar}<T> sign)
        {{
            return T.IsNegative(sign.Value) ? -Abs(value) : Abs(value);
        }}

        public static {scalar}<T> Round({scalar}<T> x) => new {scalar}<T>(T.Round(x.Value));
        public static {scalar}<T> Round({scalar}<T> x, int digits, MidpointRounding mode) => new {scalar}<T>(T.Round(x.Value, digits, mode));
        public static {scalar}<T> Round({scalar}<T> x, MidpointRounding mode) => new {scalar}<T>(T.Round(x.Value, mode));
        public static {scalar}<T> Floor({scalar}<T> x) => new {scalar}<T>(T.Floor(x.Value));
        public static {scalar}<T> Ceiling({scalar}<T> x) => new {scalar}<T>(T.Ceiling(x.Value));
        public static {scalar}<T> Truncate({scalar}<T> x) => new {scalar}<T>(T.Truncate(x.Value));

        public readonly int GetExponentByteCount()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetExponentByteCount();
            return 0;
        }}
        public readonly int GetExponentShortestBitLength()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetExponentShortestBitLength();
            return 0;
        }}
        public readonly int GetSignificandBitLength()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetSignificandBitLength();
            return 0;
        }}
        public readonly int GetSignificandByteCount()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetSignificandByteCount();
            return 0;
        }}

        public readonly bool TryWriteExponentBigEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteExponentBigEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        public readonly bool TryWriteExponentLittleEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteExponentLittleEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        public readonly bool TryWriteSignificandBigEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteSignificandBigEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        public readonly bool TryWriteSignificandLittleEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteSignificandLittleEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        #region Trigonometric Functions

        public static {scalar}<T> Sin({scalar}<T> x)
        {{
            T f = T.Sin(x.Value);
            T da = T.Cos(x.Value);
{D2("daa", "-f")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Cos({scalar}<T> x)
        {{
            T f = T.Cos(x.Value);
            T da = -T.Sin(x.Value);
{D2("daa", "-f")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Tan({scalar}<T> x)
        {{
            T f = T.Tan(x.Value);
            T da = f * f + T.One;
{D2("daa", "da * T.CreateChecked(2.0) * f")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Asin({scalar}<T> x)
        {{
            T f = T.Asin(x.Value);
            T tmp = T.One - x.Value * x.Value;
            T da = T.One / T.Sqrt(tmp);
{D2("daa", "da * x.Value / tmp")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Acos({scalar}<T> x)
        {{
            T f = T.Acos(x.Value);
            T tmp = T.One - x.Value * x.Value;
            T da = -T.One / T.Sqrt(tmp);
{D2("daa", "da * x.Value / tmp")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Atan({scalar}<T> x)
        {{
            T f = T.Atan(x.Value);
            T da = T.One / (x.Value * x.Value + T.One);
{D2("daa", "-da * da * T.CreateChecked(2.0) * x.Value")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Atan2({scalar}<T> y, {scalar}<T> x)
        {{
            T tmp = y.Value * y.Value + x.Value * x.Value;
            T f = T.Atan2(y.Value, x.Value);
            T da = x.Value / tmp;
            T db = -y.Value / tmp;
{D2("daa", "db * da * T.CreateChecked(2.0)")}{D2("dab", "db * db - da * da")}{D2("dbb", "-daa")}
            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                y.AsReadOnlySpan(), x.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), {A2("new ValueCoeff<T>(daa)")}, {A2("new ValueCoeff<T>(dab)")}, {A2("new ValueCoeff<T>(dbb)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static ({scalar}<T> Sin, {scalar}<T> Cos) SinCos({scalar}<T> x)
        {{
            return (Sin(x), Cos(x));
        }}

        public static {scalar}<T> SinPi({scalar}<T> a)
        {{
            T f = T.Sin(T.Pi * a.Value);
            T da = T.Pi * T.Cos(T.Pi * a.Value);
{D2("daa", "-T.Pi * T.Pi * f")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> CosPi({scalar}<T> a)
        {{
            T f = T.Cos(T.Pi * a.Value);
            T da = -T.Pi * T.Sin(T.Pi * a.Value);
{D2("daa", "-T.Pi * T.Pi * f")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> TanPi({scalar}<T> a)
        {{
            T f = T.Tan(T.Pi * a.Value);
            T da = T.Pi * (f * f + T.One);
{D2("daa", "T.CreateChecked(2.0) * T.Pi * f * da")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static ({scalar}<T> SinPi, {scalar}<T> CosPi) SinCosPi({scalar}<T> x)
        {{
            return (SinPi(x), CosPi(x));
        }}

        public static {scalar}<T> AtanPi({scalar}<T> a)
        {{
            T f = T.Atan(a.Value) / T.Pi;
            T da = T.One / (T.Pi * (a.Value * a.Value + T.One));
{D2("daa", "-T.CreateChecked(2.0) * a.Value * T.Pi * da * da")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Atan2Pi({scalar}<T> y, {scalar}<T> x)
        {{
            return Atan2(y, x) / T.Pi;
        }}

        public static {scalar}<T> AsinPi({scalar}<T> a)
        {{
            T f = T.Asin(a.Value) / T.Pi;
            T tmp = T.One - a.Value * a.Value;
            T da = T.One / (T.Pi * T.Sqrt(tmp));
{D2("daa", "a.Value * da / tmp")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> AcosPi({scalar}<T> a)
        {{
            T f = T.Acos(a.Value) / T.Pi;
            T tmp = T.One - a.Value * a.Value;
            T da = -T.One / (T.Pi * T.Sqrt(tmp));
{D2("daa", "a.Value * da / tmp")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Exponential Functions

        public static {scalar}<T> Exp({scalar}<T> x)
        {{
            T f = T.Exp(x.Value);
            T da = f;
{D2("daa", "f")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Exp10({scalar}<T> a)
        {{
            T f = T.Exp10(a.Value);
            T ln10 = T.Log(T.CreateChecked(10.0));
            T da = f * ln10;
{D2("daa", "da * ln10")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Exp2({scalar}<T> a)
        {{
            T f = T.Exp2(a.Value);
            T ln2 = T.Log(T.CreateChecked(2.0));
            T da = f * ln2;
{D2("daa", "da * ln2")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> ExpM1({scalar}<T> a)
        {{
            T f = T.ExpM1(a.Value);
            T da = f + T.One;
{D2("daa", "da")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Logarithmic Functions

        public static {scalar}<T> Log({scalar}<T> a)
        {{
            T f = T.Log(a.Value);
            T da = T.One / a.Value;
{D2("daa", "-da * da")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Log({scalar}<T> x, {scalar}<T> newBase) => Log(x) / Log(newBase);

        public static {scalar}<T> Log10({scalar}<T> a)
        {{
            T f = T.Log10(a.Value);
            T ln10 = T.Log(T.CreateChecked(10.0));
            T da = T.One / (a.Value * ln10);
{D2("daa", "-da / a.Value")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Log2({scalar}<T> a)
        {{
            T f = T.Log2(a.Value);
            T ln2 = T.Log(T.CreateChecked(2.0));
            T da = T.One / (a.Value * ln2);
{D2("daa", "-da / a.Value")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> LogP1({scalar}<T> a)
        {{
            T f = T.LogP1(a.Value);
            T da = T.One / (a.Value + T.One);
{D2("daa", "-da * da")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Hyperbolic Functions

        public static {scalar}<T> Sinh({scalar}<T> a)
        {{
            T f = T.Sinh(a.Value);
            T da = T.Cosh(a.Value);
{D2("daa", "f")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Cosh({scalar}<T> a)
        {{
            T f = T.Cosh(a.Value);
            T da = T.Sinh(a.Value);
{D2("daa", "f")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Tanh({scalar}<T> a)
        {{
            T f = T.Tanh(a.Value);
            T da = T.One - f * f;
{D2("daa", "-T.CreateChecked(2.0) * f * da")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Asinh({scalar}<T> a)
        {{
            T f = T.Asinh(a.Value);
            T da = T.One / T.Sqrt(a.Value * a.Value + T.One);
{D2("daa", "-a.Value * da / (a.Value * a.Value + T.One)")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Acosh({scalar}<T> a)
        {{
            T f = T.Acosh(a.Value);
            T da = T.One / T.Sqrt(a.Value * a.Value - T.One);
{D2("daa", "-a.Value * da / (a.Value * a.Value - T.One)")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Atanh({scalar}<T> a)
        {{
            T f = T.Atanh(a.Value);
            T da = T.One / (T.One - a.Value * a.Value);
{D2("daa", "T.CreateChecked(2.0) * a.Value * da * da")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Power & Root Functions

        public static {scalar}<T> Pow({scalar}<T> x, {scalar}<T> y)
        {{
            T f = T.Pow(x.Value, y.Value);
            T logX = T.Log(x.Value);
            T da = y.Value * T.Pow(x.Value, y.Value - T.One);
            T db = f * logX;
{D2("daa", "y.Value * (y.Value - T.One) * T.Pow(x.Value, y.Value - T.CreateChecked(2.0))")}{D2("dab", "T.Pow(x.Value, y.Value - T.One) * (T.One + y.Value * logX)")}{D2("dbb", "db * logX")}
            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), y.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), {A2("new ValueCoeff<T>(daa)")}, {A2("new ValueCoeff<T>(dab)")}, {A2("new ValueCoeff<T>(dbb)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Sqrt({scalar}<T> x)
        {{
            T f = T.Sqrt(x.Value);
            T da = T.One / (T.CreateChecked(2.0) * f);
{D2("daa", "-da / (T.CreateChecked(2.0) * x.Value)")}
            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Hypot({scalar}<T> x, {scalar}<T> y)
        {{
            T f = T.Sqrt(x.Value * x.Value + y.Value * y.Value);
{D2("f3", "f * f * f")}            T da = x.Value / f;
            T db = y.Value / f;
{D2("daa", "y.Value * y.Value / f3")}{D2("dab", "-x.Value * y.Value / f3")}{D2("dbb", "x.Value * x.Value / f3")}
            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), y.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), {A2("new ValueCoeff<T>(daa)")}, {A2("new ValueCoeff<T>(dab)")}, {A2("new ValueCoeff<T>(dbb)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> Cbrt({scalar}<T> a)
        {{
            T f = T.Cbrt(a.Value);
            T da = T.One / (T.CreateChecked(3.0) * f * f);
{D2("daa", "-T.CreateChecked(2.0) * da / (T.CreateChecked(3.0) * a.Value)")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static {scalar}<T> RootN({scalar}<T> a, int n)
        {{
            if (n == 0) throw new ArgumentException(""n cannot be zero"", nameof(n));
            T nT = T.CreateChecked(n);
            T f = T.Pow(a.Value, T.One / nT);
            T da = f / (nT * a.Value);
{D2("daa", "(T.One - nT) * da / (nT * a.Value)")}            {scalar}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), {A2("new ValueCoeff<T>(daa)")},
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region IEEE 754 Operations

        /// <summary>
        /// Computes <c>(x * y) + z</c> with a single rounding of the value, the way
        /// <c>IFloatingPointIeee754.FusedMultiplyAdd</c> specifies. The form is bilinear, so its
        /// derivatives are exact regardless: d/dx = y, d/dy = x, d/dz = 1, and the only non-zero
        /// second derivative is the mixed d2/dxdy = 1.
        /// </summary>
        public static {scalar}<T> FusedMultiplyAdd({scalar}<T> x, {scalar}<T> y, {scalar}<T> z)
        {{
            T f = T.FusedMultiplyAdd(x.Value, y.Value, z.Value);

            {scalar}<T> result = default;
            Kernel.Ternary<T, FalseTag,
                ValueCoeff<T>, ValueCoeff<T>, OneCoeff<T>,
                ZeroCoeff<T>, OneCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                x.AsReadOnlySpan(), y.AsReadOnlySpan(), z.AsReadOnlySpan(), f,
                new ValueCoeff<T>(y.Value), new ValueCoeff<T>(x.Value), default,
                default, default, default, default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        /// <summary>
        /// The IEEE 754 remainder <c>a - b * q</c>, where <c>q</c> is <c>a / b</c> rounded to the
        /// nearest integer with ties to even. Same function as <c>Math.IEEERemainder</c>, under the
        /// name generic math uses. Piecewise linear, so both second derivatives vanish.
        /// </summary>
        public static {scalar}<T> Ieee754Remainder({scalar}<T> a, {scalar}<T> b)
        {{
            T quotient = T.Round(a.Value / b.Value, MidpointRounding.ToEven);
            T f = T.Ieee754Remainder(a.Value, b.Value);

            {scalar}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), f,
                default, new ValueCoeff<T>(-quotient), default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        /// <summary>
        /// The next representable value above <paramref name=""x""/>.
        /// </summary>
        /// <remarks>
        /// Within a binade the step is a constant, so this is <c>x + c</c> and the derivatives are
        /// those of <c>x</c> itself — unlike <c>Round</c> or <c>Floor</c>, which are piecewise
        /// constant and therefore return a derivative-free value. Only the value moves.
        /// </remarks>
        public static {scalar}<T> BitIncrement({scalar}<T> x)
        {{
            {scalar}<T> result = x;
            result.Value = T.BitIncrement(x.Value);
            return result;
        }}

        /// <summary>
        /// The next representable value below <paramref name=""x""/>. Derivatives are preserved, for
        /// the reason given on <see cref=""BitIncrement""/>.
        /// </summary>
        public static {scalar}<T> BitDecrement({scalar}<T> x)
        {{
            {scalar}<T> result = x;
            result.Value = T.BitDecrement(x.Value);
            return result;
        }}

        /// <summary>The base-2 exponent of the value. Integer-valued, so there is nothing to differentiate.</summary>
        public static int ILogB({scalar}<T> x) => T.ILogB(x.Value);

        /// <summary>
        /// Multiplies by <c>2^n</c>. This is an exact linear scaling, so every coefficient scales
        /// with it; applying <c>ScaleB</c> per coefficient keeps that exact instead of routing it
        /// through a multiplication by a computed power of two.
        /// </summary>
        public static {scalar}<T> ScaleB({scalar}<T> x, int n)
        {{
            {scalar}<T> result = default;

            ReadOnlySpan<T> source = x.AsReadOnlySpan();
            Span<T> destination = result.AsSpan();

            for (int i = 0; i < DataLength; i++)
            {{
                destination[i] = T.ScaleB(source[i], n);
            }}

            return result;
        }}

        #endregion

        #endregion

        public override string ToString()
        {{
            return $""{{Value}} [g: ({gradientText}){hessianText}]"";
        }}
    }}
}}";
        }

        /// <summary>
        /// The inline-array backing types, emitted once for the whole compilation. The two families
        /// share data lengths -- a first-order scalar of two variables and a second-order scalar of
        /// one both need three slots -- so each length must be defined exactly once.
        /// </summary>
        private static string GenerateBuffers()
        {
            var lengths = new SortedSet<int>();
            for (int n = 1; n <= 15; n++)
            {
                lengths.Add(n + 1);
                lengths.Add((n + 1) * (n + 2) / 2);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace HyperJet");
            sb.AppendLine("{");

            foreach (int length in lengths)
            {
                sb.AppendLine($"    [InlineArray({length})]");
                sb.AppendLine($"    public struct Buffer{length}<T>");
                sb.AppendLine("    {");
                sb.AppendLine("        private T _element0;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}