using Microsoft.CodeAnalysis;
using System;
using System.Linq;
using System.Text;

namespace HyperJet.Generators
{
    [Generator]
    public class DDScalarGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(postInitContext =>
            {
                // Generate global usings for backward compatibility
                var usingsBuilder = new StringBuilder();
                usingsBuilder.AppendLine("// <auto-generated />");
                for (int n = 1; n <= 15; n++)
                {
                    usingsBuilder.AppendLine($"global using DDScalar{n} = HyperJet.DDScalar{n}<double>;");
                }
                postInitContext.AddSource("GlobalUsings.g.cs", usingsBuilder.ToString());

                // Generate DDScalar1<T> to DDScalar15<T> structs
                for (int n = 1; n <= 15; n++)
                {
                    string source = GenerateDDScalarStruct(n);
                    postInitContext.AddSource($"DDScalar{n}.g.cs", source);
                }

                // Generate the HyperJetMath free-function overloads for every dimension
                postInitContext.AddSource("HyperJetMath.Static.g.cs", GenerateHyperJetMathOverloads());
            });
        }

        /// <summary>
        /// Functions that take a single dual number and return one. Forwarded verbatim to the
        /// corresponding generic-math member of the struct.
        /// </summary>
        private static readonly string[] UnaryFunctions =
        {
            "Sin", "Cos", "Tan", "Asin", "Acos", "Atan",
            "SinPi", "CosPi", "TanPi", "AsinPi", "AcosPi", "AtanPi",
            "Exp", "Exp2", "Exp10", "ExpM1",
            "Log", "Log2", "Log10", "LogP1",
            "Sinh", "Cosh", "Tanh", "Asinh", "Acosh", "Atanh",
            "Sqrt", "Cbrt", "Abs",
        };

        /// <summary>
        /// Emits the half of <c>HyperJetMath</c> that serves the generated structs, so that
        /// <c>using static HyperJet.HyperJetMath;</c> offers <c>Sin(x)</c> for every dimension and not
        /// just for one. Everything here forwards, so there is no second copy of a derivative formula
        /// that could drift away from the struct's own.
        /// </summary>
        private static string GenerateHyperJetMathOverloads()
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Numerics;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("namespace HyperJet");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class HyperJetMath");
            sb.AppendLine("    {");

            for (int n = 1; n <= 15; n++)
            {
                string type = $"DDScalar{n}<T>";
                const string where = "where T : IFloatingPointIeee754<T>";

                sb.AppendLine($"        #region DDScalar{n} Functions");
                sb.AppendLine();

                foreach (string name in UnaryFunctions)
                {
                    sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                    sb.AppendLine($"        public static {type} {name}<T>(in {type} a) {where} => {type}.{name}(a);");
                    sb.AppendLine();
                }

                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Atan2<T>(in {type} y, in {type} x) {where} => {type}.Atan2(y, x);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Atan2Pi<T>(in {type} y, in {type} x) {where} => {type}.Atan2Pi(y, x);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Hypot<T>(in {type} a, in {type} b) {where} => {type}.Hypot(a, b);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Log<T>(in {type} a, in {type} newBase) {where} => {type}.Log(a, newBase);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Pow<T>(in {type} a, in {type} b) {where} => {type}.Pow(a, b);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} RootN<T>(in {type} a, int n) {where} => {type}.RootN(a, n);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Ieee754Remainder<T>(in {type} a, in {type} b) {where} => {type}.Ieee754Remainder(a, b);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} FusedMultiplyAdd<T>(in {type} x, in {type} y, in {type} z) {where} => {type}.FusedMultiplyAdd(x, y, z);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static ({type} Sin, {type} Cos) SinCos<T>(in {type} a) {where} => {type}.SinCos(a);");
                sb.AppendLine();
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static ({type} SinPi, {type} CosPi) SinCosPi<T>(in {type} a) {where} => {type}.SinCosPi(a);");
                sb.AppendLine();

                // A constant exponent never needs log(a), so unlike the two-operand overload this
                // one also works for a negative base.
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Raises <paramref name=\"a\"/> to a constant power. Unlike the two-operand overload this");
                sb.AppendLine("        /// never evaluates <c>log(a)</c>, so it also works for a negative base.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        public static {type} Pow<T>(in {type} a, T b) {where}");
                sb.AppendLine("        {");
                sb.AppendLine("            T two = T.One + T.One;");
                sb.AppendLine("            T f = T.Pow(a.Value, b);");
                sb.AppendLine("            T da = b * T.Pow(a.Value, b - T.One);");
                sb.AppendLine("            T daa = (b - T.One) * b * T.Pow(a.Value, b - two);");
                sb.AppendLine();
                sb.AppendLine($"            {type} result = default;");
                sb.AppendLine("            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(");
                sb.AppendLine("                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),");
                sb.AppendLine($"                result.AsSpan(), {type}.Size, {type}.Order);");
                sb.AppendLine("            return result;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        #endregion");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string[] GetVariableNames(int n)
        {
            if (n == 1) return new[] { "x" };
            if (n == 2) return new[] { "x", "y" };
            if (n == 3) return new[] { "x", "y", "z" };
            if (n == 4) return new[] { "x", "y", "z", "w" };
            
            var names = new string[n];
            for (int i = 0; i < n; i++)
            {
                names[i] = $"v{i + 1}";
            }
            return names;
        }

        private string GenerateDDScalarStruct(int n)
        {
            int size = n;
            int dataLength = (n + 1) * (n + 2) / 2;

            var variableNames = GetVariableNames(n);

            // ToString has to enumerate this dimension's coefficients. Spelling it out for two
            // variables made DDScalar1 throw from G(1) and every dimension above two print a
            // truncated gradient and Hessian.
            string gradientText = string.Join(", ", Enumerable.Range(0, n).Select(i => $"{{G({i})}}"));
            string hessianText = string.Join(", ", Enumerable.Range(0, n).Select(i =>
                "(" + string.Join(", ", Enumerable.Range(0, n).Select(j => $"{{H({i}, {j})}}")) + ")"));

            // A fixed-arity companion to Evaluate(ReadOnlySpan<T>), so that passing the wrong number
            // of offsets to a compile-time-sized scalar is a compile error rather than a throw. The
            // span local makes the target overload unambiguous; it is stack-allocated.
            var offsetParameters = string.Join(", ", Enumerable.Range(0, n).Select(i => $"T d{i}"));
            var offsetElements = string.Join(", ", Enumerable.Range(0, n).Select(i => $"d{i}"));
            string evaluateOverload = $@"        /// <summary>
        /// Evaluates the second-order Taylor expansion around the point this value was computed at.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T Evaluate({offsetParameters})
        {{{{
            ReadOnlySpan<T> d = [{offsetElements}];
            return Evaluate(d);
        }}}}";

            string variablesFactory;
            if (n == 1)
            {
                variablesFactory = @"
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar1<T> Variables(T xVal)
        {
            return Variable(0, xVal);
        }
";
            }
            else
            {
                var paramsList = string.Join(", ", variableNames.Select(v => $"T {v}Val"));
                var tupleTypes = string.Join(", ", variableNames.Select(v => $"DDScalar{n}<T> {v}"));
                var returnValues = string.Join(", ", variableNames.Select((v, idx) => $"Variable({idx}, {v}Val)"));
                variablesFactory = $@"
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ({tupleTypes}) Variables({paramsList})
        {{
            return ({returnValues});
        }}
";
            }

            return $@"// <auto-generated />
#nullable enable
using System;
using System.Globalization;
using System.Numerics;
using System.Runtime.CompilerServices;

namespace HyperJet
{{
    /// <summary>
    /// Represents a 2nd order dual number with {n} static variables (Zero-Allocation, Stack-Allocated).
    /// </summary>
    public struct DDScalar{n}<T> : 
        IFloatingPointIeee754<DDScalar{n}<T>>,
        ITrigonometricFunctions<DDScalar{n}<T>>,
        IExponentialFunctions<DDScalar{n}<T>>,
        IHyperbolicFunctions<DDScalar{n}<T>>,
        ILogarithmicFunctions<DDScalar{n}<T>>,
        IPowerFunctions<DDScalar{n}<T>>,
        IRootFunctions<DDScalar{n}<T>>
        where T : IFloatingPointIeee754<T>
    {{
        public const int Size = {size};
        public const int Order = 2;
        public const int DataLength = {dataLength};

        private Buffer{dataLength}<T> _data;

        public T Value
        {{
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            readonly get => _data[0];
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => _data[0] = value;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T G(int i)
        {{
            if (i < 0 || i >= Size)
                throw new ArgumentOutOfRangeException(nameof(i));
            return _data[1 + i];
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetG(int i, T value)
        {{
            if (i < 0 || i >= Size)
                throw new ArgumentOutOfRangeException(nameof(i));
            _data[1 + i] = value;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T H(int i, int j)
        {{
            if (i < 0 || i >= Size) throw new ArgumentOutOfRangeException(nameof(i));
            if (j < 0 || j >= Size) throw new ArgumentOutOfRangeException(nameof(j));

            int index = GetHessianIndex(i, j);
            return _data[index];
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetH(int i, int j, T value)
        {{
            if (i < 0 || i >= Size) throw new ArgumentOutOfRangeException(nameof(i));
            if (j < 0 || j >= Size) throw new ArgumentOutOfRangeException(nameof(j));

            int index = GetHessianIndex(i, j);
            _data[index] = value;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static int GetHessianIndex(int i, int j)
        {{
            if (i < j)
            {{
                return 1 + Size + (2 * Size - 1 - i) * i / 2 + j;
            }}
            else
            {{
                return 1 + Size + (2 * Size - 1 - j) * j / 2 + i;
            }}
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Span<T> AsSpan()
        {{
            return System.Runtime.InteropServices.MemoryMarshal.CreateSpan(ref Unsafe.As<Buffer{dataLength}<T>, T>(ref _data), DataLength);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly ReadOnlySpan<T> AsReadOnlySpan()
        {{
            return System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref Unsafe.As<Buffer{dataLength}<T>, T>(ref Unsafe.AsRef(in _data)), DataLength);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T[] GetGradient()
        {{
            T[] g = new T[Size];
            for (int i = 0; i < Size; i++) g[i] = G(i);
            return g;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void GetGradient(Span<T> destination)
        {{
            if (destination.Length < Size) throw new ArgumentException(""Destination span is too small."", nameof(destination));
            for (int i = 0; i < Size; i++) destination[i] = G(i);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly T[,] GetHessian()
        {{
            T[,] h = new T[Size, Size];
            for (int i = 0; i < Size; i++)
                for (int j = 0; j < Size; j++)
                    h[i, j] = H(i, j);
            return h;
        }}

        /// <summary>
        /// Evaluates the second-order Taylor expansion of the represented function around the point
        /// it was evaluated at: <c>f(x + d) = f(x) + grad(f) . d + 1/2 d^T H d</c>.
        /// </summary>
        /// <param name=""d"">The offset from the expansion point, one component per variable.</param>
        /// <remarks>
        /// For a function that is itself quadratic the expansion is exact; otherwise the error is
        /// O(|d|^3). This is the local quadratic model used by a trust-region step or a line search.
        /// </remarks>
        public readonly T Evaluate(params ReadOnlySpan<T> d)
        {{
            if (d.Length != Size)
                throw new ArgumentException($""Expected {{Size}} offsets, got {{d.Length}}."", nameof(d));

            ReadOnlySpan<T> data = AsReadOnlySpan();
            T half = T.One / (T.One + T.One);

            T result = data[0];

            for (int i = 0; i < Size; i++)
            {{
                result += data[1 + i] * d[i];
            }}

            // The Hessian is stored as the upper triangle in row order, so a single pass reaches
            // H[i,i] first and then H[i,j] for j > i. Each off-diagonal coefficient stands for two
            // symmetric terms of the quadratic form, which is exactly what cancels the one half.
            int k = 1 + Size;
            for (int i = 0; i < Size; i++)
            {{
                T di = d[i];
                result += half * data[k++] * di * di;

                for (int j = i + 1; j < Size; j++)
                {{
                    result += data[k++] * di * d[j];
                }}
            }}

            return result;
        }}

{evaluateOverload}

        #region Constructors and Factory Methods

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public DDScalar{n}(T value)
        {{
            _data = default;
            _data[0] = value;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> Constant(T value)
        {{
            return new DDScalar{n}<T>(value);
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> Variable(int index, T value)
        {{
            if (index < 0 || index >= Size)
                throw new ArgumentOutOfRangeException(nameof(index));

            DDScalar{n}<T> result = default;
            result.Value = value;
            result.SetG(index, T.One);
            return result;
        }}

{variablesFactory}

        #endregion

        #region Operators

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator -(DDScalar{n}<T> a)
        {{
            DDScalar{n}<T> result = default;
            for (int i = 0; i < DataLength; i++)
            {{
                result._data[i] = -a._data[i];
            }}
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator +(DDScalar{n}<T> a, DDScalar{n}<T> b)
        {{
            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, OneCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), a.Value + b.Value,
                default, default, default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator +(DDScalar{n}<T> a, T b)
        {{
            DDScalar{n}<T> result = a;
            result.Value += b;
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator +(T a, DDScalar{n}<T> b) => b + a;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator -(DDScalar{n}<T> a, DDScalar{n}<T> b)
        {{
            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, MinusOneCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), a.Value - b.Value,
                default, default, default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator -(DDScalar{n}<T> a, T b)
        {{
            DDScalar{n}<T> result = a;
            result.Value -= b;
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator -(T a, DDScalar{n}<T> b)
        {{
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, MinusOneCoeff<T>, ZeroCoeff<T>>(
                b.AsReadOnlySpan(), a - b.Value, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator *(DDScalar{n}<T> a, DDScalar{n}<T> b)
        {{
            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, OneCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), a.Value * b.Value,
                new ValueCoeff<T>(b.Value), new ValueCoeff<T>(a.Value), default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator *(DDScalar{n}<T> a, T b)
        {{
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), a.Value * b, new ValueCoeff<T>(b), default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator *(T a, DDScalar{n}<T> b) => b * a;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator /(DDScalar{n}<T> a, DDScalar{n}<T> b)
        {{
            T tmp = T.One / b.Value;
            T f = a.Value * tmp;
            T da = tmp;
            T db = -a.Value * tmp * tmp;
            T dab = -tmp * tmp;
            T dbb = T.CreateChecked(2.0) * a.Value * tmp * tmp * tmp;

            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), default, new ValueCoeff<T>(dab), new ValueCoeff<T>(dbb),
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator /(DDScalar{n}<T> a, T b) => a * (T.One / b);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator /(T a, DDScalar{n}<T> b)
        {{
            T tmp = T.One / b.Value;
            T f = a * tmp;
            T db = -a * tmp * tmp;
            T dbb = T.CreateChecked(2.0) * a * tmp * tmp * tmp;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                b.AsReadOnlySpan(), f, new ValueCoeff<T>(db), new ValueCoeff<T>(dbb),
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator %(DDScalar{n}<T> a, DDScalar{n}<T> b)
        {{
            // C# defines a % b as a - b * truncate(a / b) — the quotient is rounded towards zero,
            // not downwards, so Truncate (and not Floor) yields the derivative with respect to b.
            T k = T.Truncate(a.Value / b.Value);
            T f = a.Value % b.Value;
            T db = -k;

            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), f,
                default, new ValueCoeff<T>(db), default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator +(DDScalar{n}<T> a) => a;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator ++(DDScalar{n}<T> a) => a + T.One;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DDScalar{n}<T> operator --(DDScalar{n}<T> a) => a - T.One;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator DDScalar{n}<T>(T value)
        {{
            return Constant(value);
        }}

        #endregion

        #region Comparisons

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(DDScalar{n}<T> a, DDScalar{n}<T> b) => a.Value == b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(DDScalar{n}<T> a, DDScalar{n}<T> b) => a.Value != b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <(DDScalar{n}<T> a, DDScalar{n}<T> b) => a.Value < b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >(DDScalar{n}<T> a, DDScalar{n}<T> b) => a.Value > b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <=(DDScalar{n}<T> a, DDScalar{n}<T> b) => a.Value <= b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >=(DDScalar{n}<T> a, DDScalar{n}<T> b) => a.Value >= b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(DDScalar{n}<T> a, T b) => a.Value == b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(DDScalar{n}<T> a, T b) => a.Value != b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <(DDScalar{n}<T> a, T b) => a.Value < b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >(DDScalar{n}<T> a, T b) => a.Value > b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <=(DDScalar{n}<T> a, T b) => a.Value <= b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >=(DDScalar{n}<T> a, T b) => a.Value >= b;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(T a, DDScalar{n}<T> b) => a == b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(T a, DDScalar{n}<T> b) => a != b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <(T a, DDScalar{n}<T> b) => a < b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >(T a, DDScalar{n}<T> b) => a > b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator <=(T a, DDScalar{n}<T> b) => a <= b.Value;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator >=(T a, DDScalar{n}<T> b) => a >= b.Value;

        public override readonly bool Equals(object? obj) => obj is DDScalar{n}<T> other && this == other;

        public readonly bool Equals(DDScalar{n}<T> other) => Value == other.Value;

        public override readonly int GetHashCode() => Value is null ? 0 : Value.GetHashCode();

        #endregion

        #region Generic Math Support (IFloatingPoint etc.)

        public static DDScalar{n}<T> AdditiveIdentity => new DDScalar{n}<T>(T.Zero);
        public static DDScalar{n}<T> MultiplicativeIdentity => new DDScalar{n}<T>(T.One);

        public static DDScalar{n}<T> One => new DDScalar{n}<T>(T.One);
        public static DDScalar{n}<T> Zero => new DDScalar{n}<T>(T.Zero);
        public static DDScalar{n}<T> NegativeOne => new DDScalar{n}<T>(-T.One);

        public static DDScalar{n}<T> E => new DDScalar{n}<T>(T.E);
        public static DDScalar{n}<T> Pi => new DDScalar{n}<T>(T.Pi);
        public static DDScalar{n}<T> Tau => new DDScalar{n}<T>(T.Tau);

        // IEEE 754 special values. Like every other constant these carry no derivatives.
        public static DDScalar{n}<T> Epsilon => new DDScalar{n}<T>(T.Epsilon);
        public static DDScalar{n}<T> NaN => new DDScalar{n}<T>(T.NaN);
        public static DDScalar{n}<T> PositiveInfinity => new DDScalar{n}<T>(T.PositiveInfinity);
        public static DDScalar{n}<T> NegativeInfinity => new DDScalar{n}<T>(T.NegativeInfinity);
        public static DDScalar{n}<T> NegativeZero => new DDScalar{n}<T>(T.NegativeZero);

        public static int Radix => 2;

        public readonly int CompareTo(object? obj)
        {{
            if (obj is DDScalar{n}<T> other) return Value.CompareTo(other.Value);
            throw new ArgumentException(""Object is not a DDScalar"");
        }}

        public readonly int CompareTo(DDScalar{n}<T> other) => Value.CompareTo(other.Value);

        public readonly string ToString(string? format, IFormatProvider? formatProvider) => Value is null ? string.Empty : Value.ToString(format, formatProvider);

        public readonly bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {{
            if (Value is ISpanFormattable formattable)
            {{
                return formattable.TryFormat(destination, out charsWritten, format, provider);
            }}
            charsWritten = 0;
            return false;
        }}

        public readonly bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {{
            if (Value is IUtf8SpanFormattable formattable)
            {{
                return formattable.TryFormat(utf8Destination, out bytesWritten, format, provider);
            }}
            bytesWritten = 0;
            return false;
        }}

        public static DDScalar{n}<T> Parse(string s, IFormatProvider? provider) => new DDScalar{n}<T>(T.Parse(s, provider));

        public static bool TryParse(string? s, IFormatProvider? provider, out DDScalar{n}<T> result)
        {{
            if (T.TryParse(s, provider, out T? val))
            {{
                result = new DDScalar{n}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static DDScalar{n}<T> Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => new DDScalar{n}<T>(T.Parse(s, provider));

        public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out DDScalar{n}<T> result)
        {{
            if (T.TryParse(s, provider, out T? val))
            {{
                result = new DDScalar{n}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static DDScalar{n}<T> Parse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider) => new DDScalar{n}<T>(T.Parse(utf8Text, provider));

        public static bool TryParse(ReadOnlySpan<byte> utf8Text, IFormatProvider? provider, out DDScalar{n}<T> result)
        {{
            if (T.TryParse(utf8Text, provider, out T? val))
            {{
                result = new DDScalar{n}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static DDScalar{n}<T> Parse(string s, NumberStyles style, IFormatProvider? provider) => new DDScalar{n}<T>(T.Parse(s, style, provider));

        public static DDScalar{n}<T> Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) => new DDScalar{n}<T>(T.Parse(s, style, provider));

        public static bool TryParse(string? s, NumberStyles style, IFormatProvider? provider, out DDScalar{n}<T> result)
        {{
            if (T.TryParse(s, style, provider, out T? val))
            {{
                result = new DDScalar{n}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out DDScalar{n}<T> result)
        {{
            if (T.TryParse(s, style, provider, out T? val))
            {{
                result = new DDScalar{n}<T>(val);
                return true;
            }}
            result = default;
            return false;
        }}

        private static bool TryConvertFromCheckedHelper<TDest, TOther>(TOther value, out TDest result) 
            where TDest : INumberBase<TDest> 
            where TOther : INumberBase<TOther>
        {{
            return TDest.TryConvertFromChecked(value, out result!);
        }}

        private static bool TryConvertFromSaturatingHelper<TDest, TOther>(TOther value, out TDest result) 
            where TDest : INumberBase<TDest> 
            where TOther : INumberBase<TOther>
        {{
            return TDest.TryConvertFromSaturating(value, out result!);
        }}

        private static bool TryConvertFromTruncatingHelper<TDest, TOther>(TOther value, out TDest result) 
            where TDest : INumberBase<TDest> 
            where TOther : INumberBase<TOther>
        {{
            return TDest.TryConvertFromTruncating(value, out result!);
        }}

        private static bool TryConvertToCheckedHelper<TSrc, TDest>(TSrc value, out TDest result)
            where TSrc : INumberBase<TSrc>
            where TDest : INumberBase<TDest>
        {{
            return TSrc.TryConvertToChecked(value, out result!);
        }}

        private static bool TryConvertToSaturatingHelper<TSrc, TDest>(TSrc value, out TDest result)
            where TSrc : INumberBase<TSrc>
            where TDest : INumberBase<TDest>
        {{
            return TSrc.TryConvertToSaturating(value, out result!);
        }}

        private static bool TryConvertToTruncatingHelper<TSrc, TDest>(TSrc value, out TDest result)
            where TSrc : INumberBase<TSrc>
            where TDest : INumberBase<TDest>
        {{
            return TSrc.TryConvertToTruncating(value, out result!);
        }}

        private static bool IsCanonicalHelper<TSrc>(TSrc value) where TSrc : INumberBase<TSrc> => TSrc.IsCanonical(value);
        private static bool IsZeroHelper<TSrc>(TSrc value) where TSrc : INumberBase<TSrc> => TSrc.IsZero(value);

        // A conversion between TOther and the coefficient type T needs the same two-step fallback
        // INumberBase.CreateChecked performs: ask the destination first, then the source. Neither
        // side handles the case TOther == T — CreateChecked normally short-circuits that itself, and
        // here it does not, because the nominal destination is DDScalar{n}<T> rather than T.
        public static bool TryConvertFromChecked<TOther>(TOther value, out DDScalar{n}<T> result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = new DDScalar{n}<T>((T)(object)value!);
                return true;
            }}
            if (TryConvertFromCheckedHelper<T, TOther>(value, out T inner) || TryConvertToCheckedHelper<TOther, T>(value, out inner))
            {{
                result = new DDScalar{n}<T>(inner);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryConvertFromSaturating<TOther>(TOther value, out DDScalar{n}<T> result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = new DDScalar{n}<T>((T)(object)value!);
                return true;
            }}
            if (TryConvertFromSaturatingHelper<T, TOther>(value, out T inner) || TryConvertToSaturatingHelper<TOther, T>(value, out inner))
            {{
                result = new DDScalar{n}<T>(inner);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryConvertFromTruncating<TOther>(TOther value, out DDScalar{n}<T> result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = new DDScalar{n}<T>((T)(object)value!);
                return true;
            }}
            if (TryConvertFromTruncatingHelper<T, TOther>(value, out T inner) || TryConvertToTruncatingHelper<TOther, T>(value, out inner))
            {{
                result = new DDScalar{n}<T>(inner);
                return true;
            }}
            result = default;
            return false;
        }}

        public static bool TryConvertToChecked<TOther>(DDScalar{n}<T> value, out TOther result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = (TOther)(object)value.Value!;
                return true;
            }}
            return TOther.TryConvertFromChecked(value.Value, out result!)
                || TryConvertToCheckedHelper<T, TOther>(value.Value, out result);
        }}

        public static bool TryConvertToSaturating<TOther>(DDScalar{n}<T> value, out TOther result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = (TOther)(object)value.Value!;
                return true;
            }}
            return TOther.TryConvertFromSaturating(value.Value, out result!)
                || TryConvertToSaturatingHelper<T, TOther>(value.Value, out result);
        }}

        public static bool TryConvertToTruncating<TOther>(DDScalar{n}<T> value, out TOther result) where TOther : INumberBase<TOther>
        {{
            if (typeof(TOther) == typeof(T))
            {{
                result = (TOther)(object)value.Value!;
                return true;
            }}
            return TOther.TryConvertFromTruncating(value.Value, out result!)
                || TryConvertToTruncatingHelper<T, TOther>(value.Value, out result);
        }}

        public static DDScalar{n}<T> Abs(DDScalar{n}<T> value) => value.Value < T.Zero ? -value : value;

        public static bool IsCanonical(DDScalar{n}<T> value) => IsCanonicalHelper(value.Value);
        public static bool IsComplexNumber(DDScalar{n}<T> value) => false;
        public static bool IsImaginaryNumber(DDScalar{n}<T> value) => false;
        public static bool IsEvenInteger(DDScalar{n}<T> value) => T.IsEvenInteger(value.Value);
        public static bool IsOddInteger(DDScalar{n}<T> value) => T.IsOddInteger(value.Value);
        public static bool IsFinite(DDScalar{n}<T> value) => T.IsFinite(value.Value);
        public static bool IsInfinity(DDScalar{n}<T> value) => T.IsInfinity(value.Value);
        public static bool IsInteger(DDScalar{n}<T> value) => T.IsInteger(value.Value);
        public static bool IsNaN(DDScalar{n}<T> value) => T.IsNaN(value.Value);
        public static bool IsNegative(DDScalar{n}<T> value) => T.IsNegative(value.Value);
        public static bool IsNegativeInfinity(DDScalar{n}<T> value) => T.IsNegativeInfinity(value.Value);
        public static bool IsNormal(DDScalar{n}<T> value) => T.IsNormal(value.Value);
        public static bool IsPositive(DDScalar{n}<T> value) => T.IsPositive(value.Value);
        public static bool IsPositiveInfinity(DDScalar{n}<T> value) => T.IsPositiveInfinity(value.Value);
        public static bool IsRealNumber(DDScalar{n}<T> value) => T.IsRealNumber(value.Value);
        public static bool IsSubnormal(DDScalar{n}<T> value) => T.IsSubnormal(value.Value);
        public static bool IsZero(DDScalar{n}<T> value) => IsZeroHelper(value.Value);

        public static DDScalar{n}<T> MaxMagnitude(DDScalar{n}<T> x, DDScalar{n}<T> y) => T.Abs(x.Value) >= T.Abs(y.Value) ? x : y;

        public static DDScalar{n}<T> MaxMagnitudeNumber(DDScalar{n}<T> x, DDScalar{n}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return MaxMagnitude(x, y);
        }}

        public static DDScalar{n}<T> MinMagnitude(DDScalar{n}<T> x, DDScalar{n}<T> y) => T.Abs(x.Value) < T.Abs(y.Value) ? x : y;

        public static DDScalar{n}<T> MinMagnitudeNumber(DDScalar{n}<T> x, DDScalar{n}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return MinMagnitude(x, y);
        }}

        public static DDScalar{n}<T> Clamp(DDScalar{n}<T> value, DDScalar{n}<T> min, DDScalar{n}<T> max)
        {{
            if (min > max) throw new ArgumentException(""min cannot be greater than max"");
            if (value < min) return min;
            if (value > max) return max;
            return value;
        }}

        public static DDScalar{n}<T> Max(DDScalar{n}<T> x, DDScalar{n}<T> y) => x > y ? x : y;

        public static DDScalar{n}<T> Min(DDScalar{n}<T> x, DDScalar{n}<T> y) => x < y ? x : y;

        public static DDScalar{n}<T> MaxNumber(DDScalar{n}<T> x, DDScalar{n}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return x > y ? x : y;
        }}

        public static DDScalar{n}<T> MinNumber(DDScalar{n}<T> x, DDScalar{n}<T> y)
        {{
            if (T.IsNaN(x.Value)) return y;
            if (T.IsNaN(y.Value)) return x;
            return x < y ? x : y;
        }}

        public static DDScalar{n}<T> Sign(DDScalar{n}<T> value) => new DDScalar{n}<T>(T.CreateChecked(T.Sign(value.Value)));

        public static DDScalar{n}<T> CopySign(DDScalar{n}<T> value, DDScalar{n}<T> sign)
        {{
            return T.IsNegative(sign.Value) ? -Abs(value) : Abs(value);
        }}

        public static DDScalar{n}<T> Round(DDScalar{n}<T> x) => new DDScalar{n}<T>(T.Round(x.Value));
        public static DDScalar{n}<T> Round(DDScalar{n}<T> x, int digits, MidpointRounding mode) => new DDScalar{n}<T>(T.Round(x.Value, digits, mode));
        public static DDScalar{n}<T> Round(DDScalar{n}<T> x, MidpointRounding mode) => new DDScalar{n}<T>(T.Round(x.Value, mode));
        public static DDScalar{n}<T> Floor(DDScalar{n}<T> x) => new DDScalar{n}<T>(T.Floor(x.Value));
        public static DDScalar{n}<T> Ceiling(DDScalar{n}<T> x) => new DDScalar{n}<T>(T.Ceiling(x.Value));
        public static DDScalar{n}<T> Truncate(DDScalar{n}<T> x) => new DDScalar{n}<T>(T.Truncate(x.Value));

        public readonly int GetExponentByteCount()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetExponentByteCount();
            return 0;
        }}
        public readonly int GetExponentShortestBitLength()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetExponentShortestBitLength();
            return 0;
        }}
        public readonly int GetSignificandBitLength()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetSignificandBitLength();
            return 0;
        }}
        public readonly int GetSignificandByteCount()
        {{
            if (Value is IFloatingPoint<T> fp) return fp.GetSignificandByteCount();
            return 0;
        }}

        public readonly bool TryWriteExponentBigEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteExponentBigEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        public readonly bool TryWriteExponentLittleEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteExponentLittleEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        public readonly bool TryWriteSignificandBigEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteSignificandBigEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        public readonly bool TryWriteSignificandLittleEndian(Span<byte> destination, out int bytesWritten)
        {{
            if (Value is IFloatingPoint<T> fp) return fp.TryWriteSignificandLittleEndian(destination, out bytesWritten);
            bytesWritten = 0;
            return false;
        }}

        #region Trigonometric Functions

        public static DDScalar{n}<T> Sin(DDScalar{n}<T> x)
        {{
            T f = T.Sin(x.Value);
            T da = T.Cos(x.Value);
            T daa = -f;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Cos(DDScalar{n}<T> x)
        {{
            T f = T.Cos(x.Value);
            T da = -T.Sin(x.Value);
            T daa = -f;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Tan(DDScalar{n}<T> x)
        {{
            T f = T.Tan(x.Value);
            T da = f * f + T.One;
            T daa = da * T.CreateChecked(2.0) * f;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Asin(DDScalar{n}<T> x)
        {{
            T f = T.Asin(x.Value);
            T tmp = T.One - x.Value * x.Value;
            T da = T.One / T.Sqrt(tmp);
            T daa = da * x.Value / tmp;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Acos(DDScalar{n}<T> x)
        {{
            T f = T.Acos(x.Value);
            T tmp = T.One - x.Value * x.Value;
            T da = -T.One / T.Sqrt(tmp);
            T daa = da * x.Value / tmp;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Atan(DDScalar{n}<T> x)
        {{
            T f = T.Atan(x.Value);
            T da = T.One / (x.Value * x.Value + T.One);
            T daa = -da * da * T.CreateChecked(2.0) * x.Value;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Atan2(DDScalar{n}<T> y, DDScalar{n}<T> x)
        {{
            T tmp = y.Value * y.Value + x.Value * x.Value;
            T f = T.Atan2(y.Value, x.Value);
            T da = x.Value / tmp;
            T db = -y.Value / tmp;
            T daa = db * da * T.CreateChecked(2.0);
            T dab = db * db - da * da;
            T dbb = -daa;

            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                y.AsReadOnlySpan(), x.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), new ValueCoeff<T>(daa), new ValueCoeff<T>(dab), new ValueCoeff<T>(dbb),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static (DDScalar{n}<T> Sin, DDScalar{n}<T> Cos) SinCos(DDScalar{n}<T> x)
        {{
            return (Sin(x), Cos(x));
        }}

        public static DDScalar{n}<T> SinPi(DDScalar{n}<T> a)
        {{
            T f = T.Sin(T.Pi * a.Value);
            T da = T.Pi * T.Cos(T.Pi * a.Value);
            T daa = -T.Pi * T.Pi * f;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> CosPi(DDScalar{n}<T> a)
        {{
            T f = T.Cos(T.Pi * a.Value);
            T da = -T.Pi * T.Sin(T.Pi * a.Value);
            T daa = -T.Pi * T.Pi * f;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> TanPi(DDScalar{n}<T> a)
        {{
            T f = T.Tan(T.Pi * a.Value);
            T da = T.Pi * (f * f + T.One);
            T daa = T.CreateChecked(2.0) * T.Pi * f * da;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static (DDScalar{n}<T> SinPi, DDScalar{n}<T> CosPi) SinCosPi(DDScalar{n}<T> x)
        {{
            return (SinPi(x), CosPi(x));
        }}

        public static DDScalar{n}<T> AtanPi(DDScalar{n}<T> a)
        {{
            T f = T.Atan(a.Value) / T.Pi;
            T da = T.One / (T.Pi * (a.Value * a.Value + T.One));
            T daa = -T.CreateChecked(2.0) * a.Value * T.Pi * da * da;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Atan2Pi(DDScalar{n}<T> y, DDScalar{n}<T> x)
        {{
            return Atan2(y, x) / T.Pi;
        }}

        public static DDScalar{n}<T> AsinPi(DDScalar{n}<T> a)
        {{
            T f = T.Asin(a.Value) / T.Pi;
            T tmp = T.One - a.Value * a.Value;
            T da = T.One / (T.Pi * T.Sqrt(tmp));
            T daa = a.Value * da / tmp;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> AcosPi(DDScalar{n}<T> a)
        {{
            T f = T.Acos(a.Value) / T.Pi;
            T tmp = T.One - a.Value * a.Value;
            T da = -T.One / (T.Pi * T.Sqrt(tmp));
            T daa = a.Value * da / tmp;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Exponential Functions

        public static DDScalar{n}<T> Exp(DDScalar{n}<T> x)
        {{
            T f = T.Exp(x.Value);
            T da = f;
            T daa = f;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Exp10(DDScalar{n}<T> a)
        {{
            T f = T.Exp10(a.Value);
            T ln10 = T.Log(T.CreateChecked(10.0));
            T da = f * ln10;
            T daa = da * ln10;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Exp2(DDScalar{n}<T> a)
        {{
            T f = T.Exp2(a.Value);
            T ln2 = T.Log(T.CreateChecked(2.0));
            T da = f * ln2;
            T daa = da * ln2;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> ExpM1(DDScalar{n}<T> a)
        {{
            T f = T.ExpM1(a.Value);
            T da = f + T.One;
            T daa = da;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Logarithmic Functions

        public static DDScalar{n}<T> Log(DDScalar{n}<T> a)
        {{
            T f = T.Log(a.Value);
            T da = T.One / a.Value;
            T daa = -da * da;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Log(DDScalar{n}<T> x, DDScalar{n}<T> newBase) => Log(x) / Log(newBase);

        public static DDScalar{n}<T> Log10(DDScalar{n}<T> a)
        {{
            T f = T.Log10(a.Value);
            T ln10 = T.Log(T.CreateChecked(10.0));
            T da = T.One / (a.Value * ln10);
            T daa = -da / a.Value;

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Log2(DDScalar{n}<T> a)
        {{
            T f = T.Log2(a.Value);
            T ln2 = T.Log(T.CreateChecked(2.0));
            T da = T.One / (a.Value * ln2);
            T daa = -da / a.Value;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> LogP1(DDScalar{n}<T> a)
        {{
            T f = T.LogP1(a.Value);
            T da = T.One / (a.Value + T.One);
            T daa = -da * da;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Hyperbolic Functions

        public static DDScalar{n}<T> Sinh(DDScalar{n}<T> a)
        {{
            T f = T.Sinh(a.Value);
            T da = T.Cosh(a.Value);
            T daa = f;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Cosh(DDScalar{n}<T> a)
        {{
            T f = T.Cosh(a.Value);
            T da = T.Sinh(a.Value);
            T daa = f;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Tanh(DDScalar{n}<T> a)
        {{
            T f = T.Tanh(a.Value);
            T da = T.One - f * f;
            T daa = -T.CreateChecked(2.0) * f * da;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Asinh(DDScalar{n}<T> a)
        {{
            T f = T.Asinh(a.Value);
            T da = T.One / T.Sqrt(a.Value * a.Value + T.One);
            T daa = -a.Value * da / (a.Value * a.Value + T.One);
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Acosh(DDScalar{n}<T> a)
        {{
            T f = T.Acosh(a.Value);
            T da = T.One / T.Sqrt(a.Value * a.Value - T.One);
            T daa = -a.Value * da / (a.Value * a.Value - T.One);
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Atanh(DDScalar{n}<T> a)
        {{
            T f = T.Atanh(a.Value);
            T da = T.One / (T.One - a.Value * a.Value);
            T daa = T.CreateChecked(2.0) * a.Value * da * da;
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region Power & Root Functions

        public static DDScalar{n}<T> Pow(DDScalar{n}<T> x, DDScalar{n}<T> y)
        {{
            T f = T.Pow(x.Value, y.Value);
            T logX = T.Log(x.Value);
            T da = y.Value * T.Pow(x.Value, y.Value - T.One);
            T db = f * logX;
            T daa = y.Value * (y.Value - T.One) * T.Pow(x.Value, y.Value - T.CreateChecked(2.0));
            T dab = T.Pow(x.Value, y.Value - T.One) * (T.One + y.Value * logX);
            T dbb = db * logX;

            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), y.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), new ValueCoeff<T>(daa), new ValueCoeff<T>(dab), new ValueCoeff<T>(dbb),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Sqrt(DDScalar{n}<T> x)
        {{
            T f = T.Sqrt(x.Value);
            T da = T.One / (T.CreateChecked(2.0) * f);
            T daa = -da / (T.CreateChecked(2.0) * x.Value);

            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Hypot(DDScalar{n}<T> x, DDScalar{n}<T> y)
        {{
            T f = T.Sqrt(x.Value * x.Value + y.Value * y.Value);
            T f3 = f * f * f;
            T da = x.Value / f;
            T db = y.Value / f;
            T daa = y.Value * y.Value / f3;
            T dab = -x.Value * y.Value / f3;
            T dbb = x.Value * x.Value / f3;

            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>, ValueCoeff<T>>(
                x.AsReadOnlySpan(), y.AsReadOnlySpan(), f,
                new ValueCoeff<T>(da), new ValueCoeff<T>(db), new ValueCoeff<T>(daa), new ValueCoeff<T>(dab), new ValueCoeff<T>(dbb),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> Cbrt(DDScalar{n}<T> a)
        {{
            T f = T.Cbrt(a.Value);
            T da = T.One / (T.CreateChecked(3.0) * f * f);
            T daa = -T.CreateChecked(2.0) * da / (T.CreateChecked(3.0) * a.Value);
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        public static DDScalar{n}<T> RootN(DDScalar{n}<T> a, int n)
        {{
            if (n == 0) throw new ArgumentException(""n cannot be zero"", nameof(n));
            T nT = T.CreateChecked(n);
            T f = T.Pow(a.Value, T.One / nT);
            T da = f / (nT * a.Value);
            T daa = (T.One - nT) * da / (nT * a.Value);
            DDScalar{n}<T> result = default;
            Kernel.Unary<T, FalseTag, ValueCoeff<T>, ValueCoeff<T>>(
                a.AsReadOnlySpan(), f, new ValueCoeff<T>(da), new ValueCoeff<T>(daa),
                result.AsSpan(), Size, Order);
            return result;
        }}

        #endregion

        #region IEEE 754 Operations

        /// <summary>
        /// Computes <c>(x * y) + z</c> with a single rounding of the value, the way
        /// <c>IFloatingPointIeee754.FusedMultiplyAdd</c> specifies. The form is bilinear, so its
        /// derivatives are exact regardless: d/dx = y, d/dy = x, d/dz = 1, and the only non-zero
        /// second derivative is the mixed d2/dxdy = 1.
        /// </summary>
        public static DDScalar{n}<T> FusedMultiplyAdd(DDScalar{n}<T> x, DDScalar{n}<T> y, DDScalar{n}<T> z)
        {{
            T f = T.FusedMultiplyAdd(x.Value, y.Value, z.Value);

            DDScalar{n}<T> result = default;
            Kernel.Ternary<T, FalseTag,
                ValueCoeff<T>, ValueCoeff<T>, OneCoeff<T>,
                ZeroCoeff<T>, OneCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                x.AsReadOnlySpan(), y.AsReadOnlySpan(), z.AsReadOnlySpan(), f,
                new ValueCoeff<T>(y.Value), new ValueCoeff<T>(x.Value), default,
                default, default, default, default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        /// <summary>
        /// The IEEE 754 remainder <c>a - b * q</c>, where <c>q</c> is <c>a / b</c> rounded to the
        /// nearest integer with ties to even. Same function as <c>Math.IEEERemainder</c>, under the
        /// name generic math uses. Piecewise linear, so both second derivatives vanish.
        /// </summary>
        public static DDScalar{n}<T> Ieee754Remainder(DDScalar{n}<T> a, DDScalar{n}<T> b)
        {{
            T quotient = T.Round(a.Value / b.Value, MidpointRounding.ToEven);
            T f = T.Ieee754Remainder(a.Value, b.Value);

            DDScalar{n}<T> result = default;
            Kernel.Binary<T, FalseTag, OneCoeff<T>, ValueCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>, ZeroCoeff<T>>(
                a.AsReadOnlySpan(), b.AsReadOnlySpan(), f,
                default, new ValueCoeff<T>(-quotient), default, default, default,
                result.AsSpan(), Size, Order);
            return result;
        }}

        /// <summary>
        /// The next representable value above <paramref name=""x""/>.
        /// </summary>
        /// <remarks>
        /// Within a binade the step is a constant, so this is <c>x + c</c> and the derivatives are
        /// those of <c>x</c> itself — unlike <c>Round</c> or <c>Floor</c>, which are piecewise
        /// constant and therefore return a derivative-free value. Only the value moves.
        /// </remarks>
        public static DDScalar{n}<T> BitIncrement(DDScalar{n}<T> x)
        {{
            DDScalar{n}<T> result = x;
            result.Value = T.BitIncrement(x.Value);
            return result;
        }}

        /// <summary>
        /// The next representable value below <paramref name=""x""/>. Derivatives are preserved, for
        /// the reason given on <see cref=""BitIncrement""/>.
        /// </summary>
        public static DDScalar{n}<T> BitDecrement(DDScalar{n}<T> x)
        {{
            DDScalar{n}<T> result = x;
            result.Value = T.BitDecrement(x.Value);
            return result;
        }}

        /// <summary>The base-2 exponent of the value. Integer-valued, so there is nothing to differentiate.</summary>
        public static int ILogB(DDScalar{n}<T> x) => T.ILogB(x.Value);

        /// <summary>
        /// Multiplies by <c>2^n</c>. This is an exact linear scaling, so every coefficient scales
        /// with it; applying <c>ScaleB</c> per coefficient keeps that exact instead of routing it
        /// through a multiplication by a computed power of two.
        /// </summary>
        public static DDScalar{n}<T> ScaleB(DDScalar{n}<T> x, int n)
        {{
            DDScalar{n}<T> result = default;

            ReadOnlySpan<T> source = x.AsReadOnlySpan();
            Span<T> destination = result.AsSpan();

            for (int i = 0; i < DataLength; i++)
            {{
                destination[i] = T.ScaleB(source[i], n);
            }}

            return result;
        }}

        #endregion

        #endregion

        public override string ToString()
        {{
            return $""{{Value}} [g: ({gradientText}), H: ({hessianText})]"";
        }}
    }}

    [InlineArray({dataLength})]
    public struct Buffer{dataLength}<T>
    {{
        private T _element0;
    }}
}}";
        }
    }
}